### ISSUE TITLE
Proposing a logo

### ISSUE THREAD

**Issue by ghost** [JadedCtrl/shellTube#1]
It is not that pretty, just make the README.md page a little fancier.

![shelltube](https://cloud.githubusercontent.com/assets/7250745/21452795/52fcd6ea-c901-11e6-871b-bd646f2d7c49.png)

It is made with `printf '\n \033[1mshell\033[41m Tube \033[m\n'`.

There is also

```
printf '\n       \033[41m        \033[m\n \033[1mshell \033[41m  Tube  \033[m\n       \033[41m        \033[m'
```

It could be used as intro message as well.

**Comment by JadedCtrl** [comment]
With your commits, it looks like this has been added, mate. :)
